In [1]:
import pandas as pd
import numpy as np
from scipy import stats as stats
from scipy.stats import norm
from scipy.stats import chi2_contingency

In [2]:
sales=pd.read_csv("/content/BuyerRatio.csv")
sales

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [3]:
sales.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [5]:
sales_table=sales.iloc[:,1:6]
sales_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [6]:
sales_table.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

to convert observed value to expected value

In [7]:
stat, p, dof, exp = stats.chi2_contingency(sales_table) 
print(stat,"\n", p,"\n", dof,"\n", exp)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [8]:
chi2_contingency(sales_table)

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [9]:
obs = np.array([ 50,  142,  131,   70,435, 1523, 1356,  750])
exp = np.array([42.76531299,  146.81287862,  131.11756787,   72.30424052, 442.23468701, 1518.18712138, 1355.88243213,  747.69575948])

In [10]:
statistics, p_value = stats.chisquare(obs, exp, ddof = 3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


where p valuie is greater than α we reject alternative hypothesis and accept null hypothesis.